### ISSUE TITLE
Пример интеграции не работает.

### ISSUE THREAD

**Issue by XRay3D** [viva64/pvs-studio-qmake-examples#2]
Пример интеграции не работает с текущей версией креатора 4.12.4. В выводе ошибок только варнинги и ошибки GCC.
При сборке с Qt_5_15_0_MinGW_64.

Ошибка в макфайле:
C:/Users/RedFox/Documents/GitHub/GERBER_X2/G2G/PVS-Studio/C:/Users/RedFox/Documents/GitHub/GERBER_X2/clipper/C:/Users/RedFox/Documents/GitHub/GERBER_X2/clipper/clipper.cpp.plog: C:/Users/RedFox/Documents/GitHub/GERBER_X2/G2G/C:/Users/RedFox/Documents/GitHub/GERBER_X2/clipper/clipper.cpp PVS-Studio.cfg
	mkdir -p 'C:/Users/RedFox/Documents/GitHub/GERBER_X2/G2G/PVS-Studio/C:/Users/RedFox/Documents/GitHub/GERBER_X2/clipper/C:/Users/RedFox/Documents/GitHub/GERBER_X2/clipper' && rm -f 'C:/Users/RedFox/Documents/GitHub/GERBER_X2/G2G/PVS-Studio/C:/Users/RedFox/Documents/GitHub/GERBER_X2/clipper/C:/Users/RedFox/Documents/GitHub/GERBER_X2/clipper/clipper.cpp.plog' && pvs-studio-analyzer analyze --cfg 'PVS-Studio.cfg' --output-file 'C:/Users/RedFox/Documents/GitHub/GERBER_X2/G2G/PVS-Studio/C:/Users/RedFox/Documents/GitHub/GERBER_X2/clipper/C:/Users/RedFox/Documents/GitHub/GERBER_X2/clipper/clipper.cpp.plog' --source-file 'C:/Users/RedFox/Documents/GitHub/GERBER_X2/G2G/C:/Users/RedFox/Documents/GitHub/GERBER_X2/clipper/clipper.cpp' --platform linux64 --preprocessor gcc --cl-params -std=c++17 -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -DBUILD_DATE="\"Sun Jul 26 11:47:10 2020\"" -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -IC:/Users/RedFox/Documents/GitHub/GERBER_X2/G2G/forms/formsutil/ -IC:/Users/RedFox/Documents/GitHub/GERBER_X2/clipper -IC:/Users/RedFox/Documents/GitHub/GERBER_X2/excellon -IC:/Users/RedFox/Documents/GitHub/GERBER_X2/file -IC:/Users/RedFox/Documents/GitHub/GERBER_X2/gcode -IC:/Users/RedFox/Documents/GitHub/GERBER_X2/gerber -IC:/Users/RedFox/Documents/GitHub/GERBER_X2/graphicsview $(CXXFLAGS) $(DEFINES) -DPVS_STUDIO $(INCPATH) 'C:/Users/RedFox/Documents/GitHub/GERBER_X2/G2G/C:/Users/RedFox/Documents/GitHub/GERBER_X2/clipper/clipper.cpp'

**Comment by ovsyannikovviva64** [comment]
Вы пытаетесь запустить пример в Windows, а он работает только в Linux

**Comment by ovsyannikovviva64** [comment]
Извините, что долго не отвечали. К сожалению этот пример рассчитан на запуск в операционной системе Linux. В Windows напрямую он не работает.
Для того чтобы портировать этот пример для Ваших условий, необходимо сделать следующие вещи.
В этом примере есть файл PVS-Studio.pri, этот файл является "инклюдом" для проектного файла, и включается из example-1\example-1.pro. Подробнее про pri-файлы можно почитать здесь: https://wiki.qt.io/Including_.pro_Files.
Так как пример рассчитан для linux то все команды по работе с файлами и вызову анализатора в PVS-Studio.pri надо будет заменить на соответствующие для windows. 
Например в строке 114 вместо команды 'mkdir -p \'$${dir}\' ...' нужно использовать просто 'mkdir  \'$${dir}\'...' без флага -p.
А в строке 116 вместо вызова 'pvs-studio-analyzer' использовать PVS-Studio.exe (При стандартной установке он лежит в "C:\Program Files (x86)\PVS-Studio\x64\PVS-Studio.exe"), подробности можно прочитать здесь https://www.viva64.com/ru/m/0006/.
То есть заменить все Linux специфичные команды на их аналоги в Windows.

**Comment by XRay3D** [comment]
Благодарю, всё понял. С Linux мало работал. Мог сам догадаться как починить.
